### ISSUE TITLE
Certain presets missing: 6, 12

### ISSUE THREAD

**Issue by DesertCookie** [Nj0be/HandBrake-SVT-AV1-PSY#1]
These two presets are missing and can't be selected. I'm only able to jump from 13 to 11 and from 7 to 5.

![Unbenannt](https://github.com/user-attachments/assets/517d8887-e298-4e40-a5ee-b07fa84e6d49)

**Comment by Nj0be** [comment]
This behavior is intentional, as it is also present in the original HandBrake implementation. You can easily see that from [the patch responsible for adding presets](https://github.com/Nj0be/HandBrake-SVT-AV1-PSY/blob/main/patches/0005-add-presets.patch). You can see that I only add presets -2 and -3.
The reason for this is that presets 13-12 and 7-6 are identical, making it unnecessary to include both. For further details, refer to the [official SVT-AV1 presets documentation](https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/CommonQuestions.md#what-presets-do).

**Comment by DesertCookie** [comment]
Interesting. For the past two years, Handbrake's AV1 encoder allowed these options. I've been encoding with speed 6 for a while now (well, according to the GUI).

Perhaps you could add a disclaimer to the tooltip so people don't wonder about it.

**Comment by Nj0be** [comment]
> Interesting. For the past two years, Handbrake's AV1 encoder allowed these options. I've been encoding with speed 6 for a while now (well, according to the GUI).
> 
> Perhaps you could add a disclaimer to the tooltip so people don't wonder about it.

The presets 12 and 6 were removed 4 months ago with [this commit](https://github.com/HandBrake/HandBrake/commit/966f673e5bec486ecd1cfd5a8a6f31eb853ba17d). 
You were probably using an older version of HandBrake. If I install the latest stable version from github, I can't use either presets 12 or 6. 
Anyway, preset 7 should be exactly the same as preset 6. You can try both, and you should get the same encoding time.
At the moment, I don't have much time to write a good and detailed tooltip, but when I do, I'll definitely add the disclaimer to it. Thanks again
